In [17]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import os
import sys
import pickle
sys.path.append('../../')
print(sys.path)
import IPython.display as ipd
import numpy as np
import seaborn as sns; sns.set()
import librosa
import librosa.display
import matplotlib.pyplot as plt
import pandas as pd
from tools.libaudio.utils import load
from tools.libaudio.feature import melspectrogram
from tools.libaudio.waves import sin_wave
from tools.libaudio.display import show_spec, show_mel
from tools.libaudio.encodes import bit_encode
from mlutils.utils import plot, plots, to_onehot
from models.phoneme import Phoneme43
import torch
import torch.nn as nn
import torch.nn.functional as F
from mlutils.utils import time_since, update_lr
from tts.Alternative.neuravoice import CharToMel
from tts.Alternative.train import train_char2mel
from tts.Alternative.dataset import NeuraVoiceDataset
from torch.utils.data import DataLoader
import time

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
['/var/Sources/experiments/core/tts/Alternative', '/home/kaz/anaconda3/envs/core/lib/python37.zip', '/home/kaz/anaconda3/envs/core/lib/python3.7', '/home/kaz/anaconda3/envs/core/lib/python3.7/lib-dynload', '', '/home/kaz/.local/lib/python3.7/site-packages', '/home/kaz/anaconda3/envs/core/lib/python3.7/site-packages', '/home/kaz/anaconda3/envs/core/lib/python3.7/site-packages/Mako-1.0.7-py3.7.egg', '/home/kaz/anaconda3/envs/core/lib/python3.7/site-packages/IPython/extensions', '/home/kaz/.ipython', '../../', '../', '../../', '../', '../', '../', '../../']


In [9]:
z = torch.FloatTensor(torch.zeros((10, 10)))
z.shape

torch.Size([10, 10])

In [12]:
m = torch.argmax(z, dim=1)
m, m.shape

(tensor([9, 9, 9, 9, 9, 9, 9, 9, 9, 9]), torch.Size([10]))

In [21]:
y = torch.Tensor([[-7.3242e-04, -3.3569e-04, -6.1035e-05, -0.5, -0.3]])
y

tensor([[-7.3242e-04, -3.3569e-04, -6.1035e-05, -5.0000e-01, -3.0000e-01]])

In [36]:
256*2 /(2**9-1) -1

0.001956947162426559

In [37]:
512*2 /(2**9-1) -1

1.0039138943248531

In [38]:
0*2 /(2**9-1) -1

-1.0

In [25]:
bit_encode(y.numpy(), n=9)

array([[256, 256, 256, 128, 180]], dtype=int16)

In [32]:

2*bit_encode(y.numpy(), n=9) / (2**9-1) - 1

array([[ 0.00195695,  0.00195695,  0.00195695, -0.49902153, -0.29549902]])

In [31]:
torch.argmax(z, dim=1, keepdim=True)

tensor([[9],
        [9],
        [9],
        [9],
        [9],
        [9],
        [9],
        [9],
        [9],
        [9]])