In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import os
import sys
import pickle
sys.path.append('../../')
print(sys.path)
import IPython.display as ipd
import numpy as np
from tools.libaudio.feature import melspectrogram
from tools.libaudio.display import show_spec, show_mel
from mlutils.utils import plot, plots, to_onehot
from models.mlmodeldic import best_model_path_and_settings
import torch
from tts.Alternative.neuravoice2 import NewTTS, Encoder
from tts.Alternative.train import train_char2wav
from tts.Alternative.dataset import NeuraVoiceDataset
from torch.utils.data import DataLoader
import time

['/var/Sources/experiments/core/tts/Alternative', '/home/kaz/anaconda3/envs/core/lib/python37.zip', '/home/kaz/anaconda3/envs/core/lib/python3.7', '/home/kaz/anaconda3/envs/core/lib/python3.7/lib-dynload', '', '/home/kaz/.local/lib/python3.7/site-packages', '/home/kaz/anaconda3/envs/core/lib/python3.7/site-packages', '/home/kaz/anaconda3/envs/core/lib/python3.7/site-packages/Mako-1.0.7-py3.7.egg', '/home/kaz/anaconda3/envs/core/lib/python3.7/site-packages/IPython/extensions', '/home/kaz/.ipython', '../../']


In [2]:
cuda = 0
batch_size = 16
model_version = 1
model_name = f'newtts_ver{model_version}'

In [3]:
dataset = NeuraVoiceDataset(batch_size=batch_size)
loader = DataLoader(
    dataset, batch_size=batch_size, shuffle=False, collate_fn=dataset.char_to_wav, drop_last=False, num_workers=1)

In [4]:
model_path, settings = best_model_path_and_settings(model_name, 'loss_ave', is_lower_better=True)
model_path, settings

(None, None)

In [5]:
device = f'cuda:{cuda}'

In [6]:
use_best_model = False

In [7]:
if model_path and use_best_model:
    encoder = Encoder.init_from_settings(settings, model_path, device=device, **{'version': model_version})
    decoder = NewTTS.init_from_settings(settings, model_path, device=device, **{'version': model_version})
else:                             
    encoder = Encoder(K=10, hidden_size=512, bit=9, version=model_version, device=device)
    decoder = NewTTS(K=10, hidden_size=512, bit=9, version=model_version, device=device)

model version 1
Trainable Parameters: 0.874 million
model version 1
Trainable Parameters: 3.569 million


In [ ]:
losses, loss_aves, model = train_char2wav(
    encoder, decoder, loader, n_epoch=100, model_name=model_name,
    seqlen=1000, stride=100, device=device, lr=1e-4, verbose=False, check_inference=True)

0it [00:00, ?it/s]

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 251. 251. ... 210. 207. 205.]
 [264. 265. 265. ... 239. 238. 237.]
 [251. 251. 250. ... 281. 280. 277.]
 ...
 [254. 256. 258. ... 257. 258. 256.]
 [260. 258. 257. ... 254. 254. 254.]
 [252. 261. 259. ... 255. 255. 255.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 251. 251. ... 210. 207. 205.]
 [264. 265. 265. ... 239. 238. 237.]
 [251. 251. 250. ... 281. 280. 277.]
 ...
 [254. 256. 258. ... 257. 258. 256.]
 [260. 258. 257. ... 254. 254. 254.]
 [252. 261. 259. ... 255. 255. 255.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 251. 251. ... 210. 207. 205.]
 [264. 265. 265. ... 239. 238. 237.]
 [251. 251. 250. ... 281. 280. 277.]
 ...
 [254. 256. 258. ... 257. 258. 256.]
 [26

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 259. 258. ... 253. 250. 247.]
 [259. 259. 261. ... 231. 231. 232.]
 [263. 264. 264. ... 277. 276. 273.]
 ...
 [256. 252. 255. ... 256. 256. 256.]
 [258. 258. 258. ... 254. 254. 254.]
 [255. 255. 255. ... 254. 254. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 259. 258. ... 253. 250. 247.]
 [259. 259. 261. ... 231. 231. 232.]
 [263. 264. 264. ... 277. 276. 273.]
 ...
 [256. 252. 255. ... 256. 256. 256.]
 [258. 258. 258. ... 254. 254. 254.]
 [255. 255. 255. ... 254. 254. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 259. 258. ... 253. 250. 247.]
 [259. 259. 261. ... 231. 231. 232.]
 [263. 264. 264. ... 277. 276. 273.]
 ...
 [256. 252. 255. ... 256. 256. 256.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[269. 269. 269. ... 283. 284. 285.]
 [242. 241. 242. ... 261. 260. 260.]
 [250. 250. 250. ... 212. 209. 206.]
 ...
 [251. 249. 256. ... 255. 255. 255.]
 [257. 257. 257. ... 254. 254. 254.]
 [256. 255. 255. ... 254. 254. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[269. 269. 269. ... 283. 284. 285.]
 [242. 241. 242. ... 261. 260. 260.]
 [250. 250. 250. ... 212. 209. 206.]
 ...
 [251. 249. 256. ... 255. 255. 255.]
 [257. 257. 257. ... 254. 254. 254.]
 [256. 255. 255. ... 254. 254. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[269. 269. 269. ... 283. 284. 285.]
 [242. 241. 242. ... 261. 260. 260.]
 [250. 250. 250. ... 212. 209. 206.]
 ...
 [251. 249. 256. ... 255. 255. 255.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 264. 264. ... 272. 271. 271.]
 [263. 263. 263. ... 261. 261. 262.]
 [265. 263. 258. ... 266. 269. 272.]
 ...
 [254. 254. 254. ... 255. 255. 255.]
 [256. 256. 256. ... 252. 253. 256.]
 [256. 256. 255. ... 254. 254. 254.]]
epoch 0/99 iter: 0/7614 total_iter: 7-- loss ave: 5.9314 loss: 5.73 -- elapse: 1m 13s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 259. 259. ... 285. 284. 283.]
 [267. 267. 266. ... 249. 250. 251.]
 [238. 238. 239. ... 271. 268. 266.]
 ...
 [255. 253. 256. ... 256. 256. 256.]
 [256. 256. 256. ... 254. 254. 255.]
 [255. 255. 255. ... 255. 255. 255.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 259. 259. ... 285. 284. 283.]
 [267. 267. 26

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[233. 238. 242. ... 237. 242. 249.]
 [264. 267. 268. ... 259. 258. 258.]
 [246. 243. 239. ... 266. 269. 272.]
 ...
 [252. 256. 256. ... 256. 256. 256.]
 [255. 255. 255. ... 255. 253. 256.]
 [255. 255. 255. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[233. 238. 242. ... 237. 242. 249.]
 [264. 267. 268. ... 259. 258. 258.]
 [246. 243. 239. ... 266. 269. 272.]
 ...
 [252. 256. 256. ... 256. 256. 256.]
 [255. 255. 255. ... 255. 253. 256.]
 [255. 255. 255. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[233. 238. 242. ... 237. 242. 249.]
 [264. 267. 268. ... 259. 258. 258.]
 [246. 243. 239. ... 266. 269. 272.]
 ...
 [252. 256. 256. ... 256. 256. 256.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[226. 225. 223. ... 267. 258. 251.]
 [229. 229. 230. ... 256. 256. 256.]
 [272. 275. 275. ... 248. 256. 258.]
 ...
 [256. 256. 256. ... 253. 264. 273.]
 [263. 255. 245. ... 255. 256. 255.]
 [254. 254. 254. ... 257. 258. 257.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[226. 225. 223. ... 267. 258. 251.]
 [229. 229. 230. ... 256. 256. 256.]
 [272. 275. 275. ... 248. 256. 258.]
 ...
 [256. 256. 256. ... 253. 264. 273.]
 [263. 255. 245. ... 255. 256. 255.]
 [254. 254. 254. ... 257. 258. 257.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[226. 225. 223. ... 267. 258. 251.]
 [229. 229. 230. ... 256. 256. 256.]
 [272. 275. 275. ... 248. 256. 258.]
 ...
 [256. 256. 256. ... 253. 264. 273.]
 [26

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[268. 265. 262. ... 246. 252. 262.]
 [250. 247. 246. ... 256. 258. 256.]
 [236. 238. 244. ... 259. 250. 251.]
 ...
 [255. 255. 255. ... 249. 251. 251.]
 [254. 254. 254. ... 254. 256. 254.]
 [254. 254. 254. ... 265. 255. 258.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[268. 265. 262. ... 246. 252. 262.]
 [250. 247. 246. ... 256. 258. 256.]
 [236. 238. 244. ... 259. 250. 251.]
 ...
 [255. 255. 255. ... 249. 251. 251.]
 [254. 254. 254. ... 254. 256. 254.]
 [254. 254. 254. ... 265. 255. 258.]]
epoch 0/99 iter: 0/7614 total_iter: 14-- loss ave: 5.7011 loss: 5.26 -- elapse: 2m 19s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[284. 284. 283. ... 196. 192. 189.]
 [259. 258. 2

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[270. 270. 271. ... 269. 266. 264.]
 [262. 262. 262. ... 259. 256. 261.]
 [274. 274. 272. ... 266. 269. 268.]
 ...
 [255. 255. 255. ... 272. 275. 278.]
 [253. 254. 254. ... 256. 256. 255.]
 [254. 254. 254. ... 256. 254. 260.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[270. 270. 271. ... 269. 266. 264.]
 [262. 262. 262. ... 259. 256. 261.]
 [274. 274. 272. ... 266. 269. 268.]
 ...
 [255. 255. 255. ... 272. 275. 278.]
 [253. 254. 254. ... 256. 256. 255.]
 [254. 254. 254. ... 256. 254. 260.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[270. 270. 271. ... 269. 266. 264.]
 [262. 262. 262. ... 259. 256. 261.]
 [274. 274. 272. ... 266. 269. 268.]
 ...
 [255. 255. 255. ... 272. 275. 278.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[284. 284. 286. ... 262. 262. 265.]
 [247. 248. 248. ... 259. 256. 258.]
 [277. 276. 282. ... 282. 280. 278.]
 ...
 [256. 256. 256. ... 287. 285. 282.]
 [255. 253. 255. ... 259. 260. 262.]
 [255. 255. 256. ... 254. 255. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[284. 284. 286. ... 262. 262. 265.]
 [247. 248. 248. ... 259. 256. 258.]
 [277. 276. 282. ... 282. 280. 278.]
 ...
 [256. 256. 256. ... 287. 285. 282.]
 [255. 253. 255. ... 259. 260. 262.]
 [255. 255. 256. ... 254. 255. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[284. 284. 286. ... 262. 262. 265.]
 [247. 248. 248. ... 259. 256. 258.]
 [277. 276. 282. ... 282. 280. 278.]
 ...
 [256. 256. 256. ... 287. 285. 282.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[222. 225. 228. ... 280. 272. 268.]
 [263. 262. 263. ... 260. 258. 260.]
 [257. 262. 265. ... 278. 277. 277.]
 ...
 [256. 256. 256. ... 257. 256. 256.]
 [256. 256. 254. ... 204. 199. 197.]
 [256. 256. 258. ... 244. 242. 243.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[222. 225. 228. ... 280. 272. 268.]
 [263. 262. 263. ... 260. 258. 260.]
 [257. 262. 265. ... 278. 277. 277.]
 ...
 [256. 256. 256. ... 257. 256. 256.]
 [256. 256. 254. ... 204. 199. 197.]
 [256. 256. 258. ... 244. 242. 243.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[222. 225. 228. ... 280. 272. 268.]
 [263. 262. 263. ... 260. 258. 260.]
 [257. 262. 265. ... 278. 277. 277.]
 ...
 [256. 256. 256. ... 257. 256. 256.]
 [25

epoch 0/99 iter: 0/7614 total_iter: 23-- loss ave: 5.4428 loss: 4.98 -- elapse: 3m 42s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[274. 284. 291. ... 284. 287. 288.]
 [257. 256. 256. ... 267. 267. 265.]
 [251. 249. 252. ... 255. 252. 248.]
 ...
 [251. 253. 255. ... 230. 228. 224.]
 [254. 254. 255. ... 285. 289. 295.]
 [254. 252. 266. ... 266. 269. 270.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[274. 284. 291. ... 284. 287. 288.]
 [257. 256. 256. ... 267. 267. 265.]
 [251. 249. 252. ... 255. 252. 248.]
 ...
 [251. 253. 255. ... 230. 228. 224.]
 [254. 254. 255. ... 285. 289. 295.]
 [254. 252. 266. ... 266. 269. 270.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[274. 284. 291. ... 284. 287. 288.]
 [257. 256. 2

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[230. 228. 224. ... 261. 262. 264.]
 [259. 259. 260. ... 200. 192. 188.]
 [260. 260. 261. ... 231. 232. 234.]
 ...
 [257. 256. 256. ... 211. 207. 204.]
 [255. 255. 254. ... 239. 236. 235.]
 [243. 251. 274. ... 277. 276. 273.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[230. 228. 224. ... 261. 262. 264.]
 [259. 259. 260. ... 200. 192. 188.]
 [260. 260. 261. ... 231. 232. 234.]
 ...
 [257. 256. 256. ... 211. 207. 204.]
 [255. 255. 254. ... 239. 236. 235.]
 [243. 251. 274. ... 277. 276. 273.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[230. 228. 224. ... 261. 262. 264.]
 [259. 259. 260. ... 200. 192. 188.]
 [260. 260. 261. ... 231. 232. 234.]
 ...
 [257. 256. 256. ... 211. 207. 204.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[289. 288. 286. ... 267. 267. 268.]
 [258. 257. 257. ... 269. 258. 249.]
 [285. 284. 284. ... 278. 279. 281.]
 ...
 [298. 295. 292. ... 201. 205. 210.]
 [268. 268. 268. ... 282. 279. 275.]
 [256. 262. 256. ... 273. 272. 273.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[289. 288. 286. ... 267. 267. 268.]
 [258. 257. 257. ... 269. 258. 249.]
 [285. 284. 284. ... 278. 279. 281.]
 ...
 [298. 295. 292. ... 201. 205. 210.]
 [268. 268. 268. ... 282. 279. 275.]
 [256. 262. 256. ... 273. 272. 273.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[289. 288. 286. ... 267. 267. 268.]
 [258. 257. 257. ... 269. 258. 249.]
 [285. 284. 284. ... 278. 279. 281.]
 ...
 [298. 295. 292. ... 201. 205. 210.]
 [26

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 259. 258. ... 264. 263. 262.]
 [266. 264. 261. ... 288. 280. 272.]
 [279. 279. 280. ... 275. 274. 272.]
 ...
 [263. 258. 256. ... 231. 233. 234.]
 [230. 232. 234. ... 265. 269. 275.]
 [255. 254. 254. ... 258. 260. 263.]]
epoch 0/99 iter: 0/7614 total_iter: 30-- loss ave: 5.3363 loss: 4.98 -- elapse: 4m 49s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[262. 255. 250. ... 231. 229. 229.]
 [261. 258. 258. ... 287. 291. 297.]
 [276. 276. 276. ... 253. 251. 249.]
 ...
 [255. 256. 255. ... 222. 223. 223.]
 [195. 194. 194. ... 232. 233. 246.]
 [242. 240. 238. ... 250. 250. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[262. 255. 250. ... 231. 229. 229.]
 [261. 258. 2

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 252. 251. ... 269. 268. 271.]
 [260. 260. 260. ... 259. 296. 328.]
 [270. 268. 267. ... 238. 238. 239.]
 ...
 [233. 229. 225. ... 223. 225. 227.]
 [297. 293. 286. ... 218. 222. 219.]
 [259. 263. 267. ... 255. 255. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 252. 251. ... 269. 268. 271.]
 [260. 260. 260. ... 259. 296. 328.]
 [270. 268. 267. ... 238. 238. 239.]
 ...
 [233. 229. 225. ... 223. 225. 227.]
 [297. 293. 286. ... 218. 222. 219.]
 [259. 263. 267. ... 255. 255. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 252. 251. ... 269. 268. 271.]
 [260. 260. 260. ... 259. 296. 328.]
 [270. 268. 267. ... 238. 238. 239.]
 ...
 [233. 229. 225. ... 223. 225. 227.]
 [29

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[276. 278. 278. ... 251. 249. 249.]
 [249. 241. 235. ... 292. 312. 334.]
 [226. 224. 223. ... 253. 255. 256.]
 ...
 [210. 208. 205. ... 231. 234. 237.]
 [257. 262. 268. ... 226. 239. 249.]
 [272. 269. 269. ... 257. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[276. 278. 278. ... 251. 249. 249.]
 [249. 241. 235. ... 292. 312. 334.]
 [226. 224. 223. ... 253. 255. 256.]
 ...
 [210. 208. 205. ... 231. 234. 237.]
 [257. 262. 268. ... 226. 239. 249.]
 [272. 269. 269. ... 257. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[276. 278. 278. ... 251. 249. 249.]
 [249. 241. 235. ... 292. 312. 334.]
 [226. 224. 223. ... 253. 255. 256.]
 ...
 [210. 208. 205. ... 231. 234. 237.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[231. 242. 248. ... 259. 273. 262.]
 [282. 281. 283. ... 283. 285. 282.]
 [264. 266. 267. ... 259. 259. 260.]
 ...
 [199. 204. 210. ... 239. 242. 244.]
 [250. 248. 245. ... 258. 256. 257.]
 [272. 273. 272. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[231. 242. 248. ... 259. 273. 262.]
 [282. 281. 283. ... 283. 285. 282.]
 [264. 266. 267. ... 259. 259. 260.]
 ...
 [199. 204. 210. ... 239. 242. 244.]
 [250. 248. 245. ... 258. 256. 257.]
 [272. 273. 272. ... 256. 256. 256.]]
epoch 0/99 iter: 0/7614 total_iter: 37-- loss ave: 5.2457 loss: 4.73 -- elapse: 5m 53s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[267. 265. 262. ... 266. 278. 257.]
 [238. 229. 2

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 264. 264. ... 271. 248. 264.]
 [267. 259. 254. ... 231. 233. 237.]
 [271. 270. 268. ... 256. 260. 264.]
 ...
 [236. 237. 240. ... 244. 247. 249.]
 [276. 271. 268. ... 275. 273. 272.]
 [264. 266. 267. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 264. 264. ... 271. 248. 264.]
 [267. 259. 254. ... 231. 233. 237.]
 [271. 270. 268. ... 256. 260. 264.]
 ...
 [236. 237. 240. ... 244. 247. 249.]
 [276. 271. 268. ... 275. 273. 272.]
 [264. 266. 267. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 264. 264. ... 271. 248. 264.]
 [267. 259. 254. ... 231. 233. 237.]
 [271. 270. 268. ... 256. 260. 264.]
 ...
 [236. 237. 240. ... 244. 247. 249.]
 [27

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[253. 254. 255. ... 252. 251. 270.]
 [218. 214. 207. ... 240. 234. 228.]
 [234. 234. 233. ... 258. 255. 253.]
 ...
 [225. 227. 229. ... 242. 245. 247.]
 [229. 237. 249. ... 265. 265. 263.]
 [252. 253. 253. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[253. 254. 255. ... 252. 251. 270.]
 [218. 214. 207. ... 240. 234. 228.]
 [234. 234. 233. ... 258. 255. 253.]
 ...
 [225. 227. 229. ... 242. 245. 247.]
 [229. 237. 249. ... 265. 265. 263.]
 [252. 253. 253. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[253. 254. 255. ... 252. 251. 270.]
 [218. 214. 207. ... 240. 234. 228.]
 [234. 234. 233. ... 258. 255. 253.]
 ...
 [225. 227. 229. ... 242. 245. 247.]
 [22

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 258. 259. ... 276. 256. 259.]
 [227. 229. 228. ... 257. 257. 258.]
 [249. 250. 251. ... 254. 261. 257.]
 ...
 [235. 238. 241. ... 273. 275. 278.]
 [229. 241. 252. ... 224. 224. 225.]
 [256. 256. 256. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 258. 259. ... 276. 256. 259.]
 [227. 229. 228. ... 257. 257. 258.]
 [249. 250. 251. ... 254. 261. 257.]
 ...
 [235. 238. 241. ... 273. 275. 278.]
 [229. 241. 252. ... 224. 224. 225.]
 [256. 256. 256. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 258. 259. ... 276. 256. 259.]
 [227. 229. 228. ... 257. 257. 258.]
 [249. 250. 251. ... 254. 261. 257.]
 ...
 [235. 238. 241. ... 273. 275. 278.]
 [22

epoch 0/99 iter: 0/7614 total_iter: 46-- loss ave: 5.0820 loss: 4.20 -- elapse: 7m 17s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 261. 265. ... 251. 256. 255.]
 [278. 269. 255. ... 254. 254. 254.]
 [261. 262. 262. ... 256. 257. 257.]
 ...
 [247. 249. 251. ... 252. 251. 249.]
 [257. 259. 263. ... 280. 280. 280.]
 [256. 256. 256. ... 258. 258. 258.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 261. 265. ... 251. 256. 255.]
 [278. 269. 255. ... 254. 254. 254.]
 [261. 262. 262. ... 256. 257. 257.]
 ...
 [247. 249. 251. ... 252. 251. 249.]
 [257. 259. 263. ... 280. 280. 280.]
 [256. 256. 256. ... 258. 258. 258.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 261. 265. ... 251. 256. 255.]
 [278. 269. 2

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[275. 272. 248. ... 263. 242. 248.]
 [263. 245. 233. ... 255. 255. 255.]
 [262. 264. 260. ... 255. 257. 260.]
 ...
 [251. 253. 256. ... 218. 212. 209.]
 [271. 271. 272. ... 243. 241. 240.]
 [256. 256. 256. ... 254. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[275. 272. 248. ... 263. 242. 248.]
 [263. 245. 233. ... 255. 255. 255.]
 [262. 264. 260. ... 255. 257. 260.]
 ...
 [251. 253. 256. ... 218. 212. 209.]
 [271. 271. 272. ... 243. 241. 240.]
 [256. 256. 256. ... 254. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[275. 272. 248. ... 263. 242. 248.]
 [263. 245. 233. ... 255. 255. 255.]
 [262. 264. 260. ... 255. 257. 260.]
 ...
 [251. 253. 256. ... 218. 212. 209.]
 [27

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 260. 266. ... 233. 249. 261.]
 [266. 264. 261. ... 256. 256. 256.]
 [259. 262. 256. ... 258. 257. 255.]
 ...
 [250. 253. 255. ... 252. 250. 250.]
 [270. 271. 270. ... 262. 263. 265.]
 [256. 256. 256. ... 259. 256. 260.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 260. 266. ... 233. 249. 261.]
 [266. 264. 261. ... 256. 256. 256.]
 [259. 262. 256. ... 258. 257. 255.]
 ...
 [250. 253. 255. ... 252. 250. 250.]
 [270. 271. 270. ... 262. 263. 265.]
 [256. 256. 256. ... 259. 256. 260.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 260. 266. ... 233. 249. 261.]
 [266. 264. 261. ... 256. 256. 256.]
 [259. 262. 256. ... 258. 257. 255.]
 ...
 [250. 253. 255. ... 252. 250. 250.]
 [27

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[275. 249. 250. ... 236. 254. 261.]
 [263. 265. 264. ... 257. 257. 257.]
 [256. 253. 259. ... 262. 262. 261.]
 ...
 [247. 249. 251. ... 277. 276. 275.]
 [233. 232. 231. ... 273. 273. 272.]
 [256. 256. 256. ... 257. 255. 256.]]
epoch 0/99 iter: 0/7614 total_iter: 53-- loss ave: 4.9666 loss: 4.23 -- elapse: 8m 16s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[261. 244. 271. ... 256. 256. 259.]
 [259. 258. 256. ... 258. 258. 258.]
 [253. 251. 256. ... 289. 297. 294.]
 ...
 [280. 281. 281. ... 278. 278. 279.]
 [226. 227. 227. ... 262. 261. 260.]
 [256. 256. 256. ... 260. 260. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[261. 244. 271. ... 256. 256. 259.]
 [259. 258. 2

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[279. 249. 232. ... 276. 245. 234.]
 [255. 255. 255. ... 259. 259. 259.]
 [258. 252. 256. ... 225. 222. 214.]
 ...
 [270. 275. 278. ... 252. 252. 252.]
 [271. 272. 273. ... 253. 252. 252.]
 [257. 257. 257. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[279. 249. 232. ... 276. 245. 234.]
 [255. 255. 255. ... 259. 259. 259.]
 [258. 252. 256. ... 225. 222. 214.]
 ...
 [270. 275. 278. ... 252. 252. 252.]
 [271. 272. 273. ... 253. 252. 252.]
 [257. 257. 257. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[279. 249. 232. ... 276. 245. 234.]
 [255. 255. 255. ... 259. 259. 259.]
 [258. 252. 256. ... 225. 222. 214.]
 ...
 [270. 275. 278. ... 252. 252. 252.]
 [27

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[238. 259. 266. ... 253. 266. 248.]
 [254. 254. 254. ... 260. 260. 260.]
 [246. 247. 250. ... 286. 285. 287.]
 ...
 [242. 244. 247. ... 234. 235. 238.]
 [269. 267. 266. ... 257. 258. 258.]
 [258. 259. 259. ... 247. 252. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[238. 259. 266. ... 253. 266. 248.]
 [254. 254. 254. ... 260. 260. 260.]
 [246. 247. 250. ... 286. 285. 287.]
 ...
 [242. 244. 247. ... 234. 235. 238.]
 [269. 267. 266. ... 257. 258. 258.]
 [258. 259. 259. ... 247. 252. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[238. 259. 266. ... 253. 266. 248.]
 [254. 254. 254. ... 260. 260. 260.]
 [246. 247. 250. ... 286. 285. 287.]
 ...
 [242. 244. 247. ... 234. 235. 238.]
 [26

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[258. 256. 244. ... 251. 235. 259.]
 [256. 256. 256. ... 261. 259. 259.]
 [280. 281. 283. ... 225. 225. 220.]
 ...
 [235. 232. 227. ... 256. 255. 254.]
 [239. 241. 242. ... 259. 259. 259.]
 [261. 258. 259. ... 256. 263. 259.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[258. 256. 244. ... 251. 235. 259.]
 [256. 256. 256. ... 261. 259. 259.]
 [280. 281. 283. ... 225. 225. 220.]
 ...
 [235. 232. 227. ... 256. 255. 254.]
 [239. 241. 242. ... 259. 259. 259.]
 [261. 258. 259. ... 256. 263. 259.]]
epoch 0/99 iter: 0/7614 total_iter: 60-- loss ave: 4.8808 loss: 4.19 -- elapse: 9m 14s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[267. 253. 226. ... 254. 268. 253.]
 [256. 256. 2

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 248. 247. ... 266. 262. 232.]
 [257. 257. 257. ... 258. 258. 257.]
 [259. 256. 253. ... 239. 245. 247.]
 ...
 [274. 273. 271. ... 256. 257. 257.]
 [272. 271. 270. ... 258. 258. 258.]
 [257. 254. 256. ... 262. 262. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 248. 247. ... 266. 262. 232.]
 [257. 257. 257. ... 258. 258. 257.]
 [259. 256. 253. ... 239. 245. 247.]
 ...
 [274. 273. 271. ... 256. 257. 257.]
 [272. 271. 270. ... 258. 258. 258.]
 [257. 254. 256. ... 262. 262. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 248. 247. ... 266. 262. 232.]
 [257. 257. 257. ... 258. 258. 257.]
 [259. 256. 253. ... 239. 245. 247.]
 ...
 [274. 273. 271. ... 256. 257. 257.]
 [27

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[231. 260. 274. ... 249. 257. 256.]
 [258. 258. 258. ... 275. 275. 276.]
 [248. 251. 254. ... 220. 231. 253.]
 ...
 [264. 266. 266. ... 254. 253. 252.]
 [252. 252. 251. ... 256. 256. 256.]
 [263. 266. 262. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[231. 260. 274. ... 249. 257. 256.]
 [258. 258. 258. ... 275. 275. 276.]
 [248. 251. 254. ... 220. 231. 253.]
 ...
 [264. 266. 266. ... 254. 253. 252.]
 [252. 252. 251. ... 256. 256. 256.]
 [263. 266. 262. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[231. 260. 274. ... 249. 257. 256.]
 [258. 258. 258. ... 275. 275. 276.]
 [248. 251. 254. ... 220. 231. 253.]
 ...
 [264. 266. 266. ... 254. 253. 252.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 238. 240. ... 254. 255. 249.]
 [259. 259. 259. ... 260. 264. 267.]
 [258. 272. 282. ... 241. 241. 244.]
 ...
 [271. 272. 271. ... 262. 263. 263.]
 [256. 256. 256. ... 256. 256. 256.]
 [261. 260. 259. ... 252. 252. 252.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 238. 240. ... 254. 255. 249.]
 [259. 259. 259. ... 260. 264. 267.]
 [258. 272. 282. ... 241. 241. 244.]
 ...
 [271. 272. 271. ... 262. 263. 263.]
 [256. 256. 256. ... 256. 256. 256.]
 [261. 260. 259. ... 252. 252. 252.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 238. 240. ... 254. 255. 249.]
 [259. 259. 259. ... 260. 264. 267.]
 [258. 272. 282. ... 241. 241. 244.]
 ...
 [271. 272. 271. ... 262. 263. 263.]
 [25

epoch 0/99 iter: 0/7614 total_iter: 69-- loss ave: nan loss: nan -- elapse: 10m 27s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 248. 247. ... 256. 260. 262.]
 [259. 259. 261. ... 262. 260. 261.]
 [210. 201. 177. ... 275. 271. 273.]
 ...
 [253. 251. 250. ... 259. 259. 259.]
 [259. 259. 259. ... 254. 254. 254.]
 [258. 255. 260. ... 251. 251. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 248. 247. ... 256. 260. 262.]
 [259. 259. 261. ... 262. 260. 261.]
 [210. 201. 177. ... 275. 271. 273.]
 ...
 [253. 251. 250. ... 259. 259. 259.]
 [259. 259. 259. ... 254. 254. 254.]
 [258. 255. 260. ... 251. 251. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 248. 247. ... 256. 260. 262.]
 [259. 259. 261.

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 233. 256. ... 259. 259. 257.]
 [262. 262. 263. ... 258. 256. 257.]
 [280. 279. 274. ... 265. 266. 268.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [259. 259. 259. ... 251. 251. 252.]
 [266. 266. 266. ... 252. 252. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 233. 256. ... 259. 259. 257.]
 [262. 262. 263. ... 258. 256. 257.]
 [280. 279. 274. ... 265. 266. 268.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [259. 259. 259. ... 251. 251. 252.]
 [266. 266. 266. ... 252. 252. 251.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 233. 256. ... 259. 259. 257.]
 [262. 262. 263. ... 258. 256. 257.]
 [280. 279. 274. ... 265. 266. 268.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[251. 263. 258. ... 230. 230. 226.]
 [252. 256. 255. ... 282. 282. 280.]
 [223. 223. 213. ... 242. 241. 240.]
 ...
 [234. 235. 235. ... 253. 253. 253.]
 [257. 257. 257. ... 254. 256. 254.]
 [258. 258. 258. ... 253. 253. 253.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[251. 263. 258. ... 230. 230. 226.]
 [252. 256. 255. ... 282. 282. 280.]
 [223. 223. 213. ... 242. 241. 240.]
 ...
 [234. 235. 235. ... 253. 253. 253.]
 [257. 257. 257. ... 254. 256. 254.]
 [258. 258. 258. ... 253. 253. 253.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[251. 263. 258. ... 230. 230. 226.]
 [252. 256. 255. ... 282. 282. 280.]
 [223. 223. 213. ... 242. 241. 240.]
 ...
 [234. 235. 235. ... 253. 253. 253.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 247. 242. ... 277. 277. 279.]
 [239. 243. 249. ... 245. 257. 266.]
 [277. 276. 280. ... 247. 250. 254.]
 ...
 [260. 259. 259. ... 261. 259. 257.]
 [256. 256. 256. ... 255. 255. 253.]
 [254. 254. 254. ... 259. 252. 262.]]
epoch 0/99 iter: 0/7614 total_iter: 76-- loss ave: nan loss: nan -- elapse: 11m 23s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[246. 256. 263. ... 274. 272. 271.]
 [269. 272. 275. ... 254. 248. 240.]
 [245. 247. 248. ... 268. 270. 272.]
 ...
 [263. 263. 263. ... 277. 280. 282.]
 [256. 256. 256. ... 252. 252. 252.]
 [252. 252. 252. ... 256. 255. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[246. 256. 263. ... 274. 272. 271.]
 [269. 272. 275.

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[254. 251. 256. ... 227. 220. 218.]
 [253. 255. 255. ... 254. 254. 256.]
 [223. 221. 219. ... 273. 273. 273.]
 ...
 [255. 255. 255. ... 279. 277. 275.]
 [255. 255. 255. ... 248. 241. 236.]
 [251. 251. 251. ... 205. 211. 216.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[254. 251. 256. ... 227. 220. 218.]
 [253. 255. 255. ... 254. 254. 256.]
 [223. 221. 219. ... 273. 273. 273.]
 ...
 [255. 255. 255. ... 279. 277. 275.]
 [255. 255. 255. ... 248. 241. 236.]
 [251. 251. 251. ... 205. 211. 216.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[254. 251. 256. ... 227. 220. 218.]
 [253. 255. 255. ... 254. 254. 256.]
 [223. 221. 219. ... 273. 273. 273.]
 ...
 [255. 255. 255. ... 279. 277. 275.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 264. 270. ... 277. 282. 286.]
 [261. 257. 255. ... 280. 277. 269.]
 [264. 265. 264. ... 236. 234. 231.]
 ...
 [252. 252. 252. ... 208. 212. 215.]
 [254. 254. 254. ... 225. 225. 230.]
 [251. 251. 251. ... 251. 255. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 264. 270. ... 277. 282. 286.]
 [261. 257. 255. ... 280. 277. 269.]
 [264. 265. 264. ... 236. 234. 231.]
 ...
 [252. 252. 252. ... 208. 212. 215.]
 [254. 254. 254. ... 225. 225. 230.]
 [251. 251. 251. ... 251. 255. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[257. 264. 270. ... 277. 282. 286.]
 [261. 257. 255. ... 280. 277. 269.]
 [264. 265. 264. ... 236. 234. 231.]
 ...
 [252. 252. 252. ... 208. 212. 215.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[239. 239. 237. ... 233. 231. 238.]
 [287. 296. 299. ... 241. 256. 267.]
 [257. 255. 254. ... 257. 258. 261.]
 ...
 [257. 257. 257. ... 251. 254. 256.]
 [254. 252. 252. ... 251. 247. 243.]
 [252. 252. 252. ... 223. 237. 252.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[239. 239. 237. ... 233. 231. 238.]
 [287. 296. 299. ... 241. 256. 267.]
 [257. 255. 254. ... 257. 258. 261.]
 ...
 [257. 257. 257. ... 251. 254. 256.]
 [254. 252. 252. ... 251. 247. 243.]
 [252. 252. 252. ... 223. 237. 252.]]
epoch 0/99 iter: 0/7614 total_iter: 83-- loss ave: nan loss: nan -- elapse: 12m 21s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[230. 232. 233. ... 273. 276. 276.]
 [271. 262. 261.

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[281. 280. 279. ... 225. 227. 233.]
 [270. 276. 278. ... 253. 253. 253.]
 [256. 258. 259. ... 275. 275. 274.]
 ...
 [256. 255. 254. ... 277. 277. 278.]
 [251. 252. 252. ... 279. 278. 277.]
 [264. 252. 250. ... 239. 234. 226.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[281. 280. 279. ... 225. 227. 233.]
 [270. 276. 278. ... 253. 253. 253.]
 [256. 258. 259. ... 275. 275. 274.]
 ...
 [256. 255. 254. ... 277. 277. 278.]
 [251. 252. 252. ... 279. 278. 277.]
 [264. 252. 250. ... 239. 234. 226.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[281. 280. 279. ... 225. 227. 233.]
 [270. 276. 278. ... 253. 253. 253.]
 [256. 258. 259. ... 275. 275. 274.]
 ...
 [256. 255. 254. ... 277. 277. 278.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[254. 255. 255. ... 280. 275. 274.]
 [226. 225. 222. ... 285. 280. 272.]
 [277. 278. 277. ... 238. 238. 240.]
 ...
 [250. 248. 247. ... 271. 267. 264.]
 [257. 256. 256. ... 235. 232. 225.]
 [257. 256. 256. ... 236. 236. 234.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[254. 255. 255. ... 280. 275. 274.]
 [226. 225. 222. ... 285. 280. 272.]
 [277. 278. 277. ... 238. 238. 240.]
 ...
 [250. 248. 247. ... 271. 267. 264.]
 [257. 256. 256. ... 235. 232. 225.]
 [257. 256. 256. ... 236. 236. 234.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[254. 255. 255. ... 280. 275. 274.]
 [226. 225. 222. ... 285. 280. 272.]
 [277. 278. 277. ... 238. 238. 240.]
 ...
 [250. 248. 247. ... 271. 267. 264.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[266. 270. 269. ... 247. 243. 242.]
 [300. 300. 297. ... 258. 263. 268.]
 [253. 250. 246. ... 260. 260. 262.]
 ...
 [240. 237. 233. ... 248. 246. 248.]
 [281. 283. 283. ... 231. 232. 235.]
 [285. 288. 286. ... 234. 230. 226.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[266. 270. 269. ... 247. 243. 242.]
 [300. 300. 297. ... 258. 263. 268.]
 [253. 250. 246. ... 260. 260. 262.]
 ...
 [240. 237. 233. ... 248. 246. 248.]
 [281. 283. 283. ... 231. 232. 235.]
 [285. 288. 286. ... 234. 230. 226.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[266. 270. 269. ... 247. 243. 242.]
 [300. 300. 297. ... 258. 263. 268.]
 [253. 250. 246. ... 260. 260. 262.]
 ...
 [240. 237. 233. ... 248. 246. 248.]
 [28

epoch 0/99 iter: 0/7614 total_iter: 92-- loss ave: nan loss: nan -- elapse: 13m 35s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[238. 232. 229. ... 232. 238. 244.]
 [276. 282. 284. ... 260. 256. 258.]
 [263. 265. 267. ... 278. 276. 276.]
 ...
 [259. 264. 267. ... 254. 253. 251.]
 [239. 235. 232. ... 221. 216. 215.]
 [261. 272. 283. ... 290. 295. 297.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[238. 232. 229. ... 232. 238. 244.]
 [276. 282. 284. ... 260. 256. 258.]
 [263. 265. 267. ... 278. 276. 276.]
 ...
 [259. 264. 267. ... 254. 253. 251.]
 [239. 235. 232. ... 221. 216. 215.]
 [261. 272. 283. ... 290. 295. 297.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[238. 232. 229. ... 232. 238. 244.]
 [276. 282. 284.

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[268. 267. 267. ... 261. 259. 256.]
 [222. 222. 219. ... 287. 292. 291.]
 [278. 279. 279. ... 213. 218. 221.]
 ...
 [278. 279. 280. ... 251. 251. 252.]
 [240. 230. 225. ... 252. 253. 252.]
 [290. 293. 296. ... 239. 249. 268.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[268. 267. 267. ... 261. 259. 256.]
 [222. 222. 219. ... 287. 292. 291.]
 [278. 279. 279. ... 213. 218. 221.]
 ...
 [278. 279. 280. ... 251. 251. 252.]
 [240. 230. 225. ... 252. 253. 252.]
 [290. 293. 296. ... 239. 249. 268.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[268. 267. 267. ... 261. 259. 256.]
 [222. 222. 219. ... 287. 292. 291.]
 [278. 279. 279. ... 213. 218. 221.]
 ...
 [278. 279. 280. ... 251. 251. 252.]
 [24

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 264. 264. ... 277. 275. 275.]
 [305. 304. 300. ... 234. 231. 227.]
 [258. 257. 255. ... 267. 266. 265.]
 ...
 [269. 269. 268. ... 246. 245. 245.]
 [256. 257. 259. ... 243. 240. 234.]
 [318. 318. 324. ... 268. 276. 282.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 264. 264. ... 277. 275. 275.]
 [305. 304. 300. ... 234. 231. 227.]
 [258. 257. 255. ... 267. 266. 265.]
 ...
 [269. 269. 268. ... 246. 245. 245.]
 [256. 257. 259. ... 243. 240. 234.]
 [318. 318. 324. ... 268. 276. 282.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 264. 264. ... 277. 275. 275.]
 [305. 304. 300. ... 234. 231. 227.]
 [258. 257. 255. ... 267. 266. 265.]
 ...
 [269. 269. 268. ... 246. 245. 245.]
 [25

epoch 0/99 iter: 0/7614 total_iter: 99-- loss ave: nan loss: nan -- elapse: 14m 32s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[244. 251. 256. ... 269. 273. 275.]
 [274. 278. 290. ... 280. 278. 276.]
 [263. 264. 264. ... 265. 265. 265.]
 ...
 [250. 257. 265. ... 254. 253. 253.]
 [240. 247. 255. ... 249. 249. 255.]
 [225. 219. 213. ... 244. 230. 221.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[244. 251. 256. ... 269. 273. 275.]
 [274. 278. 290. ... 280. 278. 276.]
 [263. 264. 264. ... 265. 265. 265.]
 ...
 [250. 257. 265. ... 254. 253. 253.]
 [240. 247. 255. ... 249. 249. 255.]
 [225. 219. 213. ... 244. 230. 221.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[244. 251. 256. ... 269. 273. 275.]
 [274. 278. 290.

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[247. 244. 240. ... 222. 219. 222.]
 [236. 233. 228. ... 290. 290. 291.]
 [271. 273. 273. ... 256. 256. 256.]
 ...
 [255. 256. 257. ... 256. 255. 255.]
 [248. 250. 251. ... 192. 208. 220.]
 [231. 231. 232. ... 265. 256. 250.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[247. 244. 240. ... 222. 219. 222.]
 [236. 233. 228. ... 290. 290. 291.]
 [271. 273. 273. ... 256. 256. 256.]
 ...
 [255. 256. 257. ... 256. 255. 255.]
 [248. 250. 251. ... 192. 208. 220.]
 [231. 231. 232. ... 265. 256. 250.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[247. 244. 240. ... 222. 219. 222.]
 [236. 233. 228. ... 290. 290. 291.]
 [271. 273. 273. ... 256. 256. 256.]
 ...
 [255. 256. 257. ... 256. 255. 255.]
 [24

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[279. 281. 281. ... 272. 271. 269.]
 [296. 293. 284. ... 242. 243. 244.]
 [236. 232. 227. ... 254. 253. 253.]
 ...
 [242. 242. 243. ... 256. 256. 256.]
 [280. 283. 278. ... 252. 255. 256.]
 [229. 228. 226. ... 245. 237. 235.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[279. 281. 281. ... 272. 271. 269.]
 [296. 293. 284. ... 242. 243. 244.]
 [236. 232. 227. ... 254. 253. 253.]
 ...
 [242. 242. 243. ... 256. 256. 256.]
 [280. 283. 278. ... 252. 255. 256.]
 [229. 228. 226. ... 245. 237. 235.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[279. 281. 281. ... 272. 271. 269.]
 [296. 293. 284. ... 242. 243. 244.]
 [236. 232. 227. ... 254. 253. 253.]
 ...
 [242. 242. 243. ... 256. 256. 256.]
 [28

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[231. 237. 241. ... 264. 264. 263.]
 [201. 205. 217. ... 264. 265. 265.]
 [262. 265. 268. ... 254. 254. 255.]
 ...
 [251. 249. 249. ... 256. 256. 256.]
 [274. 271. 268. ... 223. 229. 236.]
 [221. 225. 227. ... 274. 271. 267.]]
epoch 0/99 iter: 0/7614 total_iter: 106-- loss ave: nan loss: nan -- elapse: 15m 30s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[275. 277. 277. ... 273. 272. 268.]
 [237. 254. 260. ... 266. 266. 266.]
 [265. 266. 267. ... 257. 257. 257.]
 ...
 [244. 244. 243. ... 257. 257. 257.]
 [229. 226. 226. ... 291. 290. 290.]
 [284. 288. 293. ... 232. 237. 245.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[275. 277. 277. ... 273. 272. 268.]
 [237. 254. 260

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[227. 226. 229. ... 248. 264. 266.]
 [287. 281. 281. ... 263. 263. 262.]
 [267. 267. 267. ... 256. 256. 256.]
 ...
 [255. 255. 255. ... 257. 257. 257.]
 [267. 267. 260. ... 250. 247. 244.]
 [241. 262. 285. ... 263. 261. 260.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[227. 226. 229. ... 248. 264. 266.]
 [287. 281. 281. ... 263. 263. 262.]
 [267. 267. 267. ... 256. 256. 256.]
 ...
 [255. 255. 255. ... 257. 257. 257.]
 [267. 267. 260. ... 250. 247. 244.]
 [241. 262. 285. ... 263. 261. 260.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[227. 226. 229. ... 248. 264. 266.]
 [287. 281. 281. ... 263. 263. 262.]
 [267. 267. 267. ... 256. 256. 256.]
 ...
 [255. 255. 255. ... 257. 257. 257.]
 [26

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 263. 261. ... 264. 262. 261.]
 [205. 199. 194. ... 255. 254. 254.]
 [261. 260. 259. ... 252. 253. 253.]
 ...
 [260. 260. 259. ... 258. 258. 258.]
 [265. 259. 256. ... 285. 279. 273.]
 [270. 271. 272. ... 241. 243. 245.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 263. 261. ... 264. 262. 261.]
 [205. 199. 194. ... 255. 254. 254.]
 [261. 260. 259. ... 252. 253. 253.]
 ...
 [260. 260. 259. ... 258. 258. 258.]
 [265. 259. 256. ... 285. 279. 273.]
 [270. 271. 272. ... 241. 243. 245.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 263. 261. ... 264. 262. 261.]
 [205. 199. 194. ... 255. 254. 254.]
 [261. 260. 259. ... 252. 253. 253.]
 ...
 [260. 260. 259. ... 258. 258. 258.]
 [26

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[269. 271. 273. ... 257. 259. 266.]
 [257. 256. 259. ... 247. 249. 249.]
 [253. 252. 252. ... 251. 251. 250.]
 ...
 [256. 256. 256. ... 258. 258. 258.]
 [289. 289. 289. ... 230. 226. 223.]
 [227. 239. 258. ... 263. 263. 262.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[269. 271. 273. ... 257. 259. 266.]
 [257. 256. 259. ... 247. 249. 249.]
 [253. 252. 252. ... 251. 251. 250.]
 ...
 [256. 256. 256. ... 258. 258. 258.]
 [289. 289. 289. ... 230. 226. 223.]
 [227. 239. 258. ... 263. 263. 262.]]
epoch 0/99 iter: 0/7614 total_iter: 113-- loss ave: nan loss: nan -- elapse: 16m 27s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[267. 265. 264. ... 272. 273. 274.]
 [250. 254. 253

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 268. 272. ... 237. 232. 226.]
 [265. 265. 265. ... 261. 261. 260.]
 [255. 256. 256. ... 256. 256. 259.]
 ...
 [256. 256. 256. ... 257. 257. 257.]
 [234. 239. 249. ... 261. 263. 265.]
 [263. 259. 254. ... 247. 247. 247.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 268. 272. ... 237. 232. 226.]
 [265. 265. 265. ... 261. 261. 260.]
 [255. 256. 256. ... 256. 256. 259.]
 ...
 [256. 256. 256. ... 257. 257. 257.]
 [234. 239. 249. ... 261. 263. 265.]
 [263. 259. 254. ... 247. 247. 247.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 268. 272. ... 237. 232. 226.]
 [265. 265. 265. ... 261. 261. 260.]
 [255. 256. 256. ... 256. 256. 259.]
 ...
 [256. 256. 256. ... 257. 257. 257.]
 [23

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[233. 224. 222. ... 255. 246. 235.]
 [265. 265. 265. ... 280. 279. 277.]
 [257. 256. 256. ... 251. 251. 251.]
 ...
 [257. 257. 257. ... 257. 257. 257.]
 [255. 256. 259. ... 278. 280. 282.]
 [249. 250. 252. ... 260. 261. 262.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[233. 224. 222. ... 255. 246. 235.]
 [265. 265. 265. ... 280. 279. 277.]
 [257. 256. 256. ... 251. 251. 251.]
 ...
 [257. 257. 257. ... 257. 257. 257.]
 [255. 256. 259. ... 278. 280. 282.]
 [249. 250. 252. ... 260. 261. 262.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[233. 224. 222. ... 255. 246. 235.]
 [265. 265. 265. ... 280. 279. 277.]
 [257. 256. 256. ... 251. 251. 251.]
 ...
 [257. 257. 257. ... 257. 257. 257.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[270. 264. 263. ... 255. 249. 247.]
 [256. 256. 256. ... 219. 234. 245.]
 [254. 254. 254. ... 256. 260. 262.]
 ...
 [258. 258. 258. ... 256. 256. 256.]
 [269. 278. 285. ... 274. 274. 272.]
 [267. 264. 261. ... 261. 261. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[270. 264. 263. ... 255. 249. 247.]
 [256. 256. 256. ... 219. 234. 245.]
 [254. 254. 254. ... 256. 260. 262.]
 ...
 [258. 258. 258. ... 256. 256. 256.]
 [269. 278. 285. ... 274. 274. 272.]
 [267. 264. 261. ... 261. 261. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[270. 264. 263. ... 255. 249. 247.]
 [256. 256. 256. ... 219. 234. 245.]
 [254. 254. 254. ... 256. 260. 262.]
 ...
 [258. 258. 258. ... 256. 256. 256.]
 [26

epoch 0/99 iter: 0/7614 total_iter: 122-- loss ave: nan loss: nan -- elapse: 17m 41s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[272. 274. 271. ... 246. 240. 237.]
 [249. 249. 249. ... 279. 276. 269.]
 [250. 250. 250. ... 231. 230. 227.]
 ...
 [258. 258. 258. ... 256. 256. 256.]
 [218. 213. 207. ... 262. 258. 258.]
 [262. 261. 261. ... 256. 255. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[272. 274. 271. ... 246. 240. 237.]
 [249. 249. 249. ... 279. 276. 269.]
 [250. 250. 250. ... 231. 230. 227.]
 ...
 [258. 258. 258. ... 256. 256. 256.]
 [218. 213. 207. ... 262. 258. 258.]
 [262. 261. 261. ... 256. 255. 254.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[272. 274. 271. ... 246. 240. 237.]
 [249. 249. 249

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 262. 267. ... 200. 215. 233.]
 [274. 272. 271. ... 246. 244. 244.]
 [253. 253. 253. ... 263. 262. 263.]
 ...
 [258. 258. 258. ... 256. 256. 256.]
 [258. 256. 255. ... 261. 257. 254.]
 [261. 260. 258. ... 259. 259. 263.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 262. 267. ... 200. 215. 233.]
 [274. 272. 271. ... 246. 244. 244.]
 [253. 253. 253. ... 263. 262. 263.]
 ...
 [258. 258. 258. ... 256. 256. 256.]
 [258. 256. 255. ... 261. 257. 254.]
 [261. 260. 258. ... 259. 259. 263.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 262. 267. ... 200. 215. 233.]
 [274. 272. 271. ... 246. 244. 244.]
 [253. 253. 253. ... 263. 262. 263.]
 ...
 [258. 258. 258. ... 256. 256. 256.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 246. 253. ... 256. 256. 257.]
 [263. 266. 270. ... 256. 255. 255.]
 [258. 261. 255. ... 270. 273. 274.]
 ...
 [257. 257. 257. ... 256. 256. 256.]
 [202. 204. 210. ... 268. 271. 273.]
 [253. 254. 256. ... 266. 269. 271.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 246. 253. ... 256. 256. 257.]
 [263. 266. 270. ... 256. 255. 255.]
 [258. 261. 255. ... 270. 273. 274.]
 ...
 [257. 257. 257. ... 256. 256. 256.]
 [202. 204. 210. ... 268. 271. 273.]
 [253. 254. 256. ... 266. 269. 271.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 246. 253. ... 256. 256. 257.]
 [263. 266. 270. ... 256. 255. 255.]
 [258. 261. 255. ... 270. 273. 274.]
 ...
 [257. 257. 257. ... 256. 256. 256.]
 [20

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[274. 278. 284. ... 269. 269. 266.]
 [193. 188. 189. ... 258. 258. 259.]
 [278. 275. 270. ... 266. 263. 262.]
 ...
 [257. 257. 257. ... 256. 256. 256.]
 [264. 262. 261. ... 253. 252. 251.]
 [262. 262. 262. ... 288. 296. 307.]]
epoch 0/99 iter: 0/7614 total_iter: 129-- loss ave: nan loss: nan -- elapse: 18m 38s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[247. 253. 259. ... 268. 262. 256.]
 [246. 255. 266. ... 256. 256. 256.]
 [264. 267. 269. ... 237. 231. 227.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [272. 270. 269. ... 262. 264. 264.]
 [261. 261. 261. ... 256. 255. 252.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[247. 253. 259. ... 268. 262. 256.]
 [246. 255. 266

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[261. 255. 254. ... 261. 262. 262.]
 [293. 290. 284. ... 244. 244. 244.]
 [259. 258. 256. ... 253. 254. 253.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [277. 279. 283. ... 272. 271. 268.]
 [262. 260. 259. ... 254. 250. 247.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[261. 255. 254. ... 261. 262. 262.]
 [293. 290. 284. ... 244. 244. 244.]
 [259. 258. 256. ... 253. 254. 253.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [277. 279. 283. ... 272. 271. 268.]
 [262. 260. 259. ... 254. 250. 247.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[261. 255. 254. ... 261. 262. 262.]
 [293. 290. 284. ... 244. 244. 244.]
 [259. 258. 256. ... 253. 254. 253.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [27

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[200. 195. 187. ... 253. 256. 258.]
 [244. 240. 239. ... 256. 256. 256.]
 [269. 273. 273. ... 265. 264. 263.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [274. 274. 275. ... 246. 245. 244.]
 [251. 254. 256. ... 241. 229. 219.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[200. 195. 187. ... 253. 256. 258.]
 [244. 240. 239. ... 256. 256. 256.]
 [269. 273. 273. ... 265. 264. 263.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [274. 274. 275. ... 246. 245. 244.]
 [251. 254. 256. ... 241. 229. 219.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[200. 195. 187. ... 253. 256. 258.]
 [244. 240. 239. ... 256. 256. 256.]
 [269. 273. 273. ... 265. 264. 263.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [27

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 260. 256. ... 255. 257. 260.]
 [246. 246. 245. ... 256. 256. 256.]
 [276. 276. 276. ... 272. 273. 274.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [216. 223. 227. ... 257. 254. 252.]
 [254. 256. 257. ... 279. 286. 281.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[264. 260. 256. ... 255. 257. 260.]
 [246. 246. 245. ... 256. 256. 256.]
 [276. 276. 276. ... 272. 273. 274.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [216. 223. 227. ... 257. 254. 252.]
 [254. 256. 257. ... 279. 286. 281.]]
epoch 0/99 iter: 0/7614 total_iter: 136-- loss ave: nan loss: nan -- elapse: 19m 33s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 263. 270. ... 252. 255. 257.]
 [253. 250. 247

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[262. 256. 249. ... 244. 246. 247.]
 [258. 258. 258. ... 253. 254. 256.]
 [261. 259. 259. ... 233. 232. 233.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [249. 249. 249. ... 256. 256. 256.]
 [315. 314. 309. ... 243. 242. 243.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[262. 256. 249. ... 244. 246. 247.]
 [258. 258. 258. ... 253. 254. 256.]
 [261. 259. 259. ... 233. 232. 233.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [249. 249. 249. ... 256. 256. 256.]
 [315. 314. 309. ... 243. 242. 243.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[262. 256. 249. ... 244. 246. 247.]
 [258. 258. 258. ... 253. 254. 256.]
 [261. 259. 259. ... 233. 232. 233.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [24

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 259. 260. ... 226. 227. 228.]
 [250. 251. 251. ... 271. 273. 271.]
 [236. 243. 248. ... 238. 241. 245.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [277. 276. 275. ... 256. 257. 257.]
 [241. 234. 238. ... 260. 264. 267.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 259. 260. ... 226. 227. 228.]
 [250. 251. 251. ... 271. 273. 271.]
 [236. 243. 248. ... 238. 241. 245.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [277. 276. 275. ... 256. 257. 257.]
 [241. 234. 238. ... 260. 264. 267.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[259. 259. 260. ... 226. 227. 228.]
 [250. 251. 251. ... 271. 273. 271.]
 [236. 243. 248. ... 238. 241. 245.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [27

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[258. 261. 263. ... 233. 231. 229.]
 [249. 248. 248. ... 242. 240. 238.]
 [261. 261. 261. ... 273. 275. 276.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [245. 239. 233. ... 253. 253. 253.]
 [187. 186. 202. ... 209. 218. 229.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[258. 261. 263. ... 233. 231. 229.]
 [249. 248. 248. ... 242. 240. 238.]
 [261. 261. 261. ... 273. 275. 276.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [245. 239. 233. ... 253. 253. 253.]
 [187. 186. 202. ... 209. 218. 229.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[258. 261. 263. ... 233. 231. 229.]
 [249. 248. 248. ... 242. 240. 238.]
 [261. 261. 261. ... 273. 275. 276.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [24

epoch 0/99 iter: 0/7614 total_iter: 145-- loss ave: nan loss: nan -- elapse: 20m 47s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[262. 264. 264. ... 277. 276. 275.]
 [256. 257. 257. ... 231. 227. 223.]
 [275. 275. 275. ... 273. 272. 271.]
 ...
 [255. 255. 255. ... 256. 256. 256.]
 [250. 249. 250. ... 246. 252. 253.]
 [275. 276. 273. ... 256. 256. 255.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[262. 264. 264. ... 277. 276. 275.]
 [256. 257. 257. ... 231. 227. 223.]
 [275. 275. 275. ... 273. 272. 271.]
 ...
 [255. 255. 255. ... 256. 256. 256.]
 [250. 249. 250. ... 246. 252. 253.]
 [275. 276. 273. ... 256. 256. 255.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[262. 264. 264. ... 277. 276. 275.]
 [256. 257. 257

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[255. 256. 259. ... 263. 259. 256.]
 [249. 249. 248. ... 285. 284. 285.]
 [254. 253. 251. ... 246. 243. 240.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [254. 253. 253. ... 245. 241. 238.]
 [302. 311. 315. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[255. 256. 259. ... 263. 259. 256.]
 [249. 249. 248. ... 285. 284. 285.]
 [254. 253. 251. ... 246. 243. 240.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [254. 253. 253. ... 245. 241. 238.]
 [302. 311. 315. ... 256. 256. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[255. 256. 259. ... 263. 259. 256.]
 [249. 249. 248. ... 285. 284. 285.]
 [254. 253. 251. ... 246. 243. 240.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[242. 244. 245. ... 242. 253. 262.]
 [259. 258. 260. ... 271. 269. 266.]
 [229. 230. 231. ... 245. 250. 256.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [248. 248. 246. ... 237. 235. 235.]
 [268. 264. 258. ... 247. 251. 255.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[242. 244. 245. ... 242. 253. 262.]
 [259. 258. 260. ... 271. 269. 266.]
 [229. 230. 231. ... 245. 250. 256.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [248. 248. 246. ... 237. 235. 235.]
 [268. 264. 258. ... 247. 251. 255.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[242. 244. 245. ... 242. 253. 262.]
 [259. 258. 260. ... 271. 269. 266.]
 [229. 230. 231. ... 245. 250. 256.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [24

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[226. 225. 225. ... 268. 270. 272.]
 [258. 262. 266. ... 234. 234. 234.]
 [265. 265. 266. ... 267. 274. 276.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [256. 256. 256. ... 240. 242. 243.]
 [233. 231. 233. ... 249. 250. 249.]]
epoch 0/99 iter: 0/7614 total_iter: 152-- loss ave: nan loss: nan -- elapse: 21m 44s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[230. 231. 232. ... 270. 269. 270.]
 [237. 238. 238. ... 250. 247. 245.]
 [277. 277. 277. ... 268. 268. 271.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [254. 254. 255. ... 244. 247. 251.]
 [234. 235. 233. ... 254. 253. 253.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[230. 231. 232. ... 270. 269. 270.]
 [237. 238. 238

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 257. 255. ... 274. 275. 274.]
 [265. 270. 269. ... 265. 264. 263.]
 [278. 277. 276. ... 274. 275. 275.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [254. 254. 253. ... 264. 263. 265.]
 [259. 256. 256. ... 256. 256. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 257. 255. ... 274. 275. 274.]
 [265. 270. 269. ... 265. 264. 263.]
 [278. 277. 276. ... 274. 275. 275.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [254. 254. 253. ... 264. 263. 265.]
 [259. 256. 256. ... 256. 256. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 257. 255. ... 274. 275. 274.]
 [265. 270. 269. ... 265. 264. 263.]
 [278. 277. 276. ... 274. 275. 275.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[273. 278. 280. ... 263. 264. 265.]
 [254. 252. 250. ... 254. 254. 251.]
 [257. 256. 256. ... 247. 243. 243.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [241. 245. 243. ... 274. 275. 276.]
 [250. 254. 258. ... 266. 261. 264.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[273. 278. 280. ... 263. 264. 265.]
 [254. 252. 250. ... 254. 254. 251.]
 [257. 256. 256. ... 247. 243. 243.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [241. 245. 243. ... 274. 275. 276.]
 [250. 254. 258. ... 266. 261. 264.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[273. 278. 280. ... 263. 264. 265.]
 [254. 252. 250. ... 254. 254. 251.]
 [257. 256. 256. ... 247. 243. 243.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [24

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 251. 248. ... 258. 257. 256.]
 [257. 259. 261. ... 255. 258. 260.]
 [235. 236. 237. ... 217. 226. 226.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [242. 239. 238. ... 274. 273. 271.]
 [255. 257. 255. ... 261. 266. 267.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[252. 251. 248. ... 258. 257. 256.]
 [257. 259. 261. ... 255. 258. 260.]
 [235. 236. 237. ... 217. 226. 226.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [242. 239. 238. ... 274. 273. 271.]
 [255. 257. 255. ... 261. 266. 267.]]
epoch 0/99 iter: 0/7614 total_iter: 159-- loss ave: nan loss: nan -- elapse: 22m 42s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[274. 280. 284. ... 233. 234. 235.]
 [264. 264. 260

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[274. 276. 276. ... 265. 265. 265.]
 [233. 234. 235. ... 260. 256. 255.]
 [272. 270. 269. ... 235. 236. 239.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [243. 245. 246. ... 262. 261. 259.]
 [253. 253. 250. ... 260. 260. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[274. 276. 276. ... 265. 265. 265.]
 [233. 234. 235. ... 260. 256. 255.]
 [272. 270. 269. ... 235. 236. 239.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [243. 245. 246. ... 262. 261. 259.]
 [253. 253. 250. ... 260. 260. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[274. 276. 276. ... 265. 265. 265.]
 [233. 234. 235. ... 260. 256. 255.]
 [272. 270. 269. ... 235. 236. 239.]
 ...
 [256. 256. 256. ... 255. 255. 255.]
 [24

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 266. 268. ... 250. 251. 252.]
 [261. 260. 259. ... 271. 258. 245.]
 [275. 275. 272. ... 234. 237. 239.]
 ...
 [256. 256. 256. ... 256. 256. 255.]
 [259. 262. 264. ... 244. 242. 240.]
 [248. 251. 259. ... 258. 257. 257.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 266. 268. ... 250. 251. 252.]
 [261. 260. 259. ... 271. 258. 245.]
 [275. 275. 272. ... 234. 237. 239.]
 ...
 [256. 256. 256. ... 256. 256. 255.]
 [259. 262. 264. ... 244. 242. 240.]
 [248. 251. 259. ... 258. 257. 257.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 266. 268. ... 250. 251. 252.]
 [261. 260. 259. ... 271. 258. 245.]
 [275. 275. 272. ... 234. 237. 239.]
 ...
 [256. 256. 256. ... 256. 256. 255.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[241. 241. 240. ... 268. 267. 266.]
 [263. 263. 262. ... 252. 255. 267.]
 [260. 256. 255. ... 228. 230. 229.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [273. 274. 274. ... 227. 227. 227.]
 [264. 263. 261. ... 258. 258. 258.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[241. 241. 240. ... 268. 267. 266.]
 [263. 263. 262. ... 252. 255. 267.]
 [260. 256. 255. ... 228. 230. 229.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [273. 274. 274. ... 227. 227. 227.]
 [264. 263. 261. ... 258. 258. 258.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[241. 241. 240. ... 268. 267. 266.]
 [263. 263. 262. ... 252. 255. 267.]
 [260. 256. 255. ... 228. 230. 229.]
 ...
 [256. 256. 256. ... 256. 256. 256.]
 [27

epoch 0/99 iter: 0/7614 total_iter: 168-- loss ave: nan loss: nan -- elapse: 23m 54s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 256. 255. ... 237. 239. 242.]
 [258. 251. 253. ... 266. 268. 249.]
 [228. 225. 222. ... 259. 258. 257.]
 ...
 [255. 255. 255. ... 256. 256. 256.]
 [272. 272. 270. ... 248. 250. 252.]
 [264. 261. 261. ... 257. 257. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 256. 255. ... 237. 239. 242.]
 [258. 251. 253. ... 266. 268. 249.]
 [228. 225. 222. ... 259. 258. 257.]
 ...
 [255. 255. 255. ... 256. 256. 256.]
 [272. 272. 270. ... 248. 250. 252.]
 [264. 261. 261. ... 257. 257. 261.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[256. 256. 255. ... 237. 239. 242.]
 [258. 251. 253

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 261. 260. ... 269. 269. 269.]
 [253. 269. 253. ... 256. 245. 256.]
 [236. 237. 238. ... 266. 266. 266.]
 ...
 [255. 255. 255. ... 256. 256. 256.]
 [264. 262. 261. ... 272. 271. 272.]
 [258. 258. 260. ... 259. 256. 258.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 261. 260. ... 269. 269. 269.]
 [253. 269. 253. ... 256. 245. 256.]
 [236. 237. 238. ... 266. 266. 266.]
 ...
 [255. 255. 255. ... 256. 256. 256.]
 [264. 262. 261. ... 272. 271. 272.]
 [258. 258. 260. ... 259. 256. 258.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[263. 261. 260. ... 269. 269. 269.]
 [253. 269. 253. ... 256. 245. 256.]
 [236. 237. 238. ... 266. 266. 266.]
 ...
 [255. 255. 255. ... 256. 256. 256.]
 [26

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 260. 260. ... 245. 245. 246.]
 [262. 264. 252. ... 267. 258. 239.]
 [242. 244. 247. ... 253. 255. 256.]
 ...
 [255. 255. 255. ... 256. 258. 258.]
 [250. 247. 246. ... 272. 271. 271.]
 [251. 258. 267. ... 260. 255. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 260. 260. ... 245. 245. 246.]
 [262. 264. 252. ... 267. 258. 239.]
 [242. 244. 247. ... 253. 255. 256.]
 ...
 [255. 255. 255. ... 256. 258. 258.]
 [250. 247. 246. ... 272. 271. 271.]
 [251. 258. 267. ... 260. 255. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 260. 260. ... 245. 245. 246.]
 [262. 264. 252. ... 267. 258. 239.]
 [242. 244. 247. ... 253. 255. 256.]
 ...
 [255. 255. 255. ... 256. 258. 258.]
 [25

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[227. 227. 228. ... 258. 256. 254.]
 [249. 246. 269. ... 252. 256. 256.]
 [235. 238. 238. ... 264. 264. 263.]
 ...
 [256. 256. 256. ... 251. 253. 260.]
 [231. 229. 228. ... 217. 221. 224.]
 [258. 259. 258. ... 249. 255. 259.]]
epoch 0/99 iter: 0/7614 total_iter: 175-- loss ave: nan loss: nan -- elapse: 24m 51s speed 0.1 steps/sec
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[265. 264. 263. ... 276. 275. 275.]
 [253. 245. 264. ... 262. 253. 252.]
 [228. 231. 232. ... 261. 261. 262.]
 ...
 [256. 256. 256. ... 256. 255. 256.]
 [227. 228. 228. ... 248. 249. 250.]
 [259. 258. 258. ... 251. 249. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[265. 264. 263. ... 276. 275. 275.]
 [253. 245. 264

sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 260. 259. ... 267. 266. 264.]
 [256. 239. 260. ... 263. 251. 250.]
 [236. 232. 231. ... 241. 239. 238.]
 ...
 [256. 256. 256. ... 254. 256. 257.]
 [238. 240. 242. ... 273. 273. 272.]
 [260. 258. 257. ... 246. 254. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 260. 259. ... 267. 266. 264.]
 [256. 239. 260. ... 263. 251. 250.]
 [236. 232. 231. ... 241. 239. 238.]
 ...
 [256. 256. 256. ... 254. 256. 257.]
 [238. 240. 242. ... 273. 273. 272.]
 [260. 258. 257. ... 246. 254. 256.]]
sample [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y [[260. 260. 259. ... 267. 266. 264.]
 [256. 239. 260. ... 263. 251. 250.]
 [236. 232. 231. ... 241. 239. 238.]
 ...
 [256. 256. 256. ... 254. 256. 257.]
 [23

In [ ]:
#plot(loss_aves)

In [ ]:
#plots([losses, loss_aves], labels=['losses', 'loss_aves'])